<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="桂宝元" ignored="0" name="vivoX9" tests="4" failures="1" timestamp="11 九月 2018 02:52:49 GMT" time="138.036" errors="0">
  <testcase name="@AfterClass deletePost" time="0.693" classname="gby.testng.testcase.PublishPostCase">
    <failure type="java.lang.AssertionError" message="检查点检查出错误">
      <![CDATA[java.lang.AssertionError: 检查点检查出错误
at gby.appium.utils.AssertUtils.checkIsNextPage(AssertUtils.java:148)
at gby.testng.testcase.PublishPostCase.deletePost(PublishPostCase.java:66)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass deletePost -->
  <testcase name="f" time="56.953" classname="gby.testng.testcase.InitDriverCase"/>
  <testcase name="intoPublisPostPage" time="18.539" classname="gby.testng.testcase.PublishPostCase"/>
  <testcase name="publishRoom" time="26.833" classname="gby.testng.testcase.PublishPostCase">
    <skipped/>
  </testcase> <!-- publishRoom -->
  <testcase name="publishRoom" time="15.581" classname="gby.testng.testcase.PublishPostCase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at gby.appium.page.FindRoommateBasePage.inputText(FindRoommateBasePage.java:50)
at gby.testng.testcase.PublishPostCase.publishRoom(PublishPostCase.java:50)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- publishRoom -->
</testsuite> <!-- vivoX9 -->
